### ISSUE TITLE
fully auto triangular arbitrage

### ISSUE THREAD

**Issue by onthetunnel** [balinskia/binance-arbitrage-trading#1]
Hello , if this project can do :
fully automatic monitoring and auto multiply total amount of btc(binance minimum order limit is 0.001 Btc) and auto order 3 or more profit road(after calc the higher profit of triangular arbitrage pair like :
road1 :BTC-XX1-ETH-BTC 0.02% profit
road2 : BTC-XX2-ETH-BTC 0.018% profit
road3 : BTC-XX3-BNB-BTC 0.011% profit ) on few second and 24/7. running without problem or crash , i will donate 0.005-0.01 BTC , Hope someone can do this work , Thanks You !

**Comment by K4mB** [comment]
hahaha i saw you in other github asking for the same, you can find a coder in fiverrr

**Comment by balinskia** [comment]
@onthetunnel  Please contact me albert@balin.ski

**Comment by onthetunnel** [comment]
Hello Dear Balinskia , Can you develop auto triangular arbitrage for binance please...as i promise i will send btc to you ! if  can  24/7 without any problem... Thanks You!
